admin_service/export/models.py
from sqlalchemy.dialects.postgresql import ARRAY, JSON
from admin_service.extensions import db
from sqlalchemy.orm import backref, relationship


class ExportICSConfig(db.Model):
    __tablename__ = 'exportics_configs'
    id = db.Column(db.Integer, primary_key=True)
    calendar_prodid = db.Column(db.String(100))
    query = db.Column(db.String(200))
    config_slug = db.Column(db.String(200))
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    team = relationship("Team", backref=backref("exportics_config", uselist=False))

admin_service/models.py
# -*- coding: utf-8 -*-

from .auth.models import User

admin_service/__init__.py
from .app import create_app, create_celery

admin_service/api/__init__.py
# -*- coding: utf-8 -*-

from .views import *

admin_service/api/views.py
import uuid
import flask_restless.manager
from flask import (Blueprint, render_template, current_app, abort)
from sqlalchemy.orm.exc import NoResultFound
from admin_service.auth.models import Team
from admin_service.events.models import SuggestedEvent

import trafaret as t

from ..extensions import manager, csrf


def get_team_by_name(name):
    try:
        return Team.query.filter(Team.name == name).one().id
    except NoResultFound:
        raise t.DataError('Team not found')


EVENT_SUGGESTION_TRAFARET = t.Dict({
    'title': t.String,
    'agenda': t.String,
    'social': t.String(allow_blank=True) | t.Null,
    'place': t.String(allow_blank=True),
    'registration_url': t.URL(allow_blank=True) | t.Null,
    'image_url': t.URL(allow_blank=True) | t.String(max_length=0, allow_blank=True),
    'level': t.Enum('NONE', 'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR'),
    'when_start': t.String,
    'when_end': (t.String(allow_blank=True) >>
                 (lambda x: None if not x else x)) | t.Null,
    'only_date': t.StrBool(),
    'team': t.String() >> get_team_by_name,
    'submitter_email': t.Email(),
    'secret': t.String
}).make_optional('secret', 'social')


def pre_get_many(**kw):
    abort(405)


def pre_put_single(instance_id=None, data=None, **kw):
    data.update(EVENT_SUGGESTION_TRAFARET.check(data))


def suggested_event_deserializer(data):
    try:
        validated = EVENT_SUGGESTION_TRAFARET.check(data)
    except t.DataError as e:
        return abort(400, e.error)
    validated['secret'] = uuid.uuid4().hex
    return SuggestedEvent(**validated)


def initialize_api(app):
    # List all Flask-Restless APIs here
    with app.app_context():
        manager.create_api(SuggestedEvent, methods=['GET', 'POST', 'PUT'],
                           app=app,
                           url_prefix='/api/v1',
                           preprocessors={
                               # 'GET_SINGLE': [pre_get_single],
                               'GET_MANY': [pre_get_many],
                               'PUT_SINGLE': [pre_put_single]
                               },
                           deserializer=suggested_event_deserializer)

    # Disable CSRF check for REST API
    # FIXME: I know :(
    api_blueprints = [v for x, v in app.blueprints.items()
                      if v.import_name == flask_restless.manager.__name__]
    for blueprint in api_blueprints:
        csrf.exempt(blueprint)


api = Blueprint('api', __name__)

admin_service/app.py
#pylint:disable-msg=W0612
import datetime

import os
import dateutil
from flask import Flask, request, render_template, g
from flask.ext import login
from celery import Celery
from admin_service.events.client import EventsServiceAPI
from admin_service.events.models import SuggestedEvent

from .extensions import (db, mail, pages, manager, login_manager, babel,
    migrate, csrf, celery, cache)

# blueprints
from .frontend import frontend
from .auth import auth
from .api import api, initialize_api
from .events import events
from .digestmonkey import digestmonkey
from .export import export

__all__ = ('create_app', 'create_celery', )

BLUEPRINTS = (
    frontend,
    auth,
    api,
    events,
    digestmonkey,
    export
)


def create_app(config=None, app_name='admin_service', blueprints=None):
    app = Flask(app_name,
        static_folder=os.path.join(os.path.dirname(__file__), '..', 'static'),
        template_folder="templates"
    )

    app.config.from_object('admin_service.config')
    # app.config.from_pyfile('../local.cfg', silent=True)
    if config:
        app.config.from_pyfile(config)

    if blueprints is None:
        blueprints = BLUEPRINTS

    blueprints_fabrics(app, blueprints)
    extensions_fabrics(app)
    api_fabrics(app)  # this must be called after extensions_fabrics
    configure_logging(app)
    template_filters(app)

    error_pages(app)
    gvars(app)

    return app


def create_celery(app):
    celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    TaskBase = celery.Task
    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery


def blueprints_fabrics(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def extensions_fabrics(app):
    db.init_app(app)
    mail.init_app(app)
    babel.init_app(app)
    pages.init_app(app)
    login_manager.init_app(app)
    manager.init_app(app, flask_sqlalchemy_db=db)
    migrate.init_app(app, db)
    csrf.init_app(app)
    celery.config_from_object(app.config)
    cache.init_app(app)


def api_fabrics(app):
    initialize_api(app)


def error_pages(app):
    # HTTP error pages definitions

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("misc/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("misc/404.html"), 404

    @app.errorhandler(405)
    def method_not_allowed(error):
        return render_template("misc/405.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("misc/500.html"), 500


def gvars(app):
    @app.before_first_request
    def events_api():
        app.events_api = EventsServiceAPI(app.config['EVENTS_SERVICE_URL'])

    @app.before_request
    def gdebug():
        if app.debug:
            g.debug = True
        else:
            g.debug = False

    from .models import User

    @login_manager.user_loader
    def load_user(userid):
        try:
            return User.query.get(int(userid))
        except (TypeError, ValueError):
            pass

    @app.before_request
    def guser():
        g.user = login.current_user

    @app.context_processor
    def inject_user():
        try:
            return {'user': g.user}
        except AttributeError:
            return {'user': None}

    @app.context_processor
    def dateutils():
        today = datetime.date.today()
        cw_monday = today + datetime.timedelta(days=-today.weekday())
        cw_sunday = today + datetime.timedelta(days=7 - today.weekday() - 1)
        nw_monday = today + datetime.timedelta(days=-today.weekday() + 7)
        nw_sunday = today + datetime.timedelta(days=7 - today.weekday() + 6)
        return dict(cw_monday=cw_monday,
                    cw_sunday=cw_sunday,
                    nw_monday=nw_monday,
                    nw_sunday=nw_sunday)

    @app.context_processor
    def suggested_events():
        if g.user.is_authenticated:
            count = SuggestedEvent.query.filter(SuggestedEvent.team == g.user.team.id).count()
            return dict(suggested_events_count=count)
        return dict()

    @babel.localeselector
    def get_locale():
        if g.user:
            if hasattr(g.user, 'ui_lang'):
                return g.user.ui_lang

        accept_languages = app.config.get('ACCEPT_LANGUAGES')
        return request.accept_languages.best_match(accept_languages)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler(app.config['MAIL_SERVER'],
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)


def template_filters(app):
    @app.template_filter('strfdatetime')
    def _jinja2_filter_datetime(date, fmt=None):
        date = dateutil.parser.parse(date)
        native = date.replace(tzinfo=None)
        return native.strftime('%Y-%m-%d %H:%M')

    @app.template_filter('strfdate')
    def _jinja2_filter_date(date, fmt=None):
        date = dateutil.parser.parse(date)
        native = date.replace(tzinfo=None)
        return native.strftime('%Y-%m-%d')

    @app.template_filter('strftime')
    def _jinja2_filter_date(date, fmt):
        return date.strftime(fmt)

admin_service/digestmonkey/__init__.py
from .views import digestmonkey

admin_service/events/__init__.py
from .views import events

admin_service/events/client/__init__.py
import json
import requests


class EventsServiceAPIError(Exception):
    def __init__(self, errors=None):
        if not errors:
            errors = []
        super().__init__()
        self.errors = errors

    def __str__(self):
        return '; '.join(self.errors)


class EventsServiceAPI:
    def __init__(self, url):
        self.url = url
        self.session = requests.Session()

    def register_provider(self, name):
        response = self.session.post('{}/providers'.format(self.url),
                                     json={'name': name})
        return response.json()['key']

    def get_events(self, api_key, offset=0, count=10, sorting=None, query=None):
        if not sorting:
            sorting = ''
        response = self.session.get('{}/events?count={}&offset={}&order_by={}&query={}'.
                                    format(self.url, count, offset, sorting, query),
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        data = response.json()
        events = []
        for event in data.pop('events'):
            event['metainfo'] = json.loads(event.pop('metainfo'))
            events.append(event)
        data['events'] = events
        return data

    def get_event(self, api_key, id_):
        response = self.session.get('{}/events/{}'.
                                    format(self.url, id_),
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        data = response.json()
        data['metainfo'] = json.loads(data.pop('metainfo'))
        return data

    def add_event(self, api_key, metainfo, **kwargs):
        data = kwargs.copy()
        data.update({'metainfo': json.dumps(metainfo)})
        response = self.session.post('{}/events'.
                                     format(self.url),
                                     json=data,
                                     headers={'Client-Key': api_key})
        self.process_errors(response)
        return response.headers['location']

    def edit_event(self, api_key, id_, metainfo, **kwargs):
        data = kwargs.copy()
        data.update({'metainfo': json.dumps(metainfo)})
        response = self.session.put('{}/events/{}'.
                                    format(self.url, id_),
                                    json=data,
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        return response.headers['location']

    def delete_event(self, api_key, id_):
        response = self.session.delete('{}/events/{}'.
                                       format(self.url, id_),
                                       headers={'Client-Key': api_key})
        self.process_errors(response)

    def process_errors(self, response):
        if response.status_code > 299:
            if response.status_code == 400:
                raise EventsServiceAPIError(['{}: {} [api]'.format(k, v) for k, v in response.json().items()])
            raise EventsServiceAPIError(['Events Service returned {} error'.format(response.status_code)])

admin_service/export/__init__.py
from .views import export

admin_service/export/views.py
# -*- coding: utf-8 -*-
import uuid

from flask import (Blueprint, render_template, g, request, url_for,
    current_app, send_from_directory, json, redirect, make_response, abort)

from flask.ext.login import login_required
from admin_service.export.ics import generate_ics
from admin_service.export.models import ExportICSConfig

from ..extensions import pages, csrf, db
from ..tasks import do_some_stuff
import trafaret as t

export = Blueprint('export', __name__, url_prefix='/export/', template_folder="templates")


@export.route('index')
@login_required
def index():
    return render_template('export/index.html')


@export.route('ics')
@login_required
def export_ics():
    if not g.user.team.exportics_config or \
            not g.user.team.exportics_config.calendar_prodid or \
            not g.user.team.exportics_config.config_slug:
        return redirect(url_for('export.setup_ics'))
    return render_template('export/ics.html',
                           config=g.user.team.exportics_config)


SETUP_FORM = t.Dict({
                     'calendar_prodid': t.String,
                     'query': t.String(allow_blank=True)
                    }).ignore_extra('_csrf_token')


@export.route('ics/setup', methods=['POST', 'GET'])
@login_required
def setup_ics():
    g.errors = []
    if request.method == 'POST':
        do_setup()
        if not g.errors:
            return redirect(url_for('export.export_ics'))
    return render_template('export/setup_ics.html',
                           errors=g.errors,
                           initial=g.user.team.exportics_config)


def do_setup():
    try:
        data = SETUP_FORM.check(request.form.to_dict())
    except t.DataError as e:
        g.errors += ['{}: {}'.format(key, value)
                     for key, value in e.error.items()]
        return

    sess = db.session()
    if not g.user.team.exportics_config:
        config = ExportICSConfig(team_id=g.user.team.id,
                                 config_slug=uuid.uuid4().hex)
        sess.add(config)
        sess.commit()
    else:
        config = g.user.team.exportics_config
    if not g.user.team.exportics_config.config_slug:
        data['config_slug'] = uuid.uuid4().hex
    sess.query(ExportICSConfig).filter(ExportICSConfig.id == config.id).update(data)
    sess.commit()


@export.route('ics/<slug>/calendar.ics')
def ics_feed(slug):
    sess = db.session()
    config = sess.query(ExportICSConfig).filter(ExportICSConfig.config_slug == slug).first()
    events_token = config.team.events_token
    events = current_app.events_api.get_events(
        events_token,
        offset=0,
        count=100,
        sorting='-when_start',
        query=config.query)
    calendar = generate_ics(events['events'], config)
    r = make_response(calendar)
    r.headers['Content-Type'] = 'text/calendar; charset=utf-8'
    r.headers['Content-Disposition'] = 'attachment;filename=' + slug[:8] + '.ics'
    return r

admin_service/frontend/__init__.py
from .views import frontend

admin_service/frontend/views.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, render_template, g, request, url_for,
    current_app, send_from_directory, json, redirect, make_response, abort)

from flask.ext.login import login_required

from ..extensions import pages, csrf
from ..tasks import do_some_stuff

frontend = Blueprint('frontend', __name__, template_folder="templates")


@frontend.route('/')
def index():
    # Run background task inside of view
    # do_some_stuff.delay()
    return render_template('frontend/index.html')


@frontend.route('/docs/', defaults={'path': 'index'})
@frontend.route('/docs/<path:path>/', endpoint='page')
def page(path):
    # Documentation views
    _page = pages.get_or_404(path)
    return render_template('page.html', page=_page)


@frontend.route('/robots.txt')
def static_from_root():
    # Static items
    return send_from_directory(current_app.static_folder, request.path[1:])


@frontend.route('/favicon.ico')
def favicon():
    return redirect('/static/favicon.png')

admin_service/templates/base.html
<!DOCTYPE html>
<html lang="{{ lang|default('en') }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
  <link rel="shortcut icon" href="/static/favicon.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">

  <title>{% block title %}{{ page_title|default(_('evnt')) }}{% endblock %}</title>
  {% block before_includes %}
  {% endblock %}

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/flakes/css/all.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/gridforms/gridforms/gridforms.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  {% block include_css %}
  {% endblock %}

  <script src="{{ url_for('static', filename='libs/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='libs/snapjs/snap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='libs/responsive-elements/responsive-elements.js') }}"></script>
  <script src="{{ url_for('static', filename='libs/gridforms/gridforms/gridforms.js') }}"></script>
  {% block include_js %}
  {% endblock %}

{% block extramedia %}{% endblock %}

</head>
<body {% block body_id %}{% endblock %}>

    <div class="flakes-frame">

        {% include "nav.html" %}

        <div class="flakes-content">

            <div class="flakes-mobile-top-bar">
                <a href="" class="navigation-expand-target">
                    <img src="{{ url_for('static', filename='libs/flakes/img/site-wide/navigation-expand-target.png') }}" height="26px">
                </a>
            </div>

            <div class="view-wrap">
                {% if user.is_authenticated %}
                    {% if suggested_events_count > 0 %}
                        <p class="flakes-message information">You've got <a href="{{ url_for('events.suggested_events_list') }}">{{ suggested_events_count }} suggested events</a></p>
                    {% endif %}
                {% endif %}
                {% block content %}
                <h1>Evnt</h1>
                {% endblock %}
            </div>
        </div>
    </div>

  <script src="{{ url_for('static', filename='code.js') }}"></script>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-69380903-1', 'auto');
      ga('send', 'pageview');

  </script>
</body>
</html>

admin_service/templates/nav.html
<div class="flakes-navigation">
    <a href="index.html" class="logo">
        <!--<img src="{{ url_for('static', filename='libs/flakes/img/logo.png') }}" width="120">-->
    </a>

    <ul>
        <li class="title">Applications</li>
        {% if user.is_authenticated %}
            <li><a href="{{ url_for('events.events_list') }}">Events Database</a></li>
            <li><a href="{{ url_for('events.suggested_events_list') }}">Suggested Events ({{ suggested_events_count }})</a></li>
            <li><a href="{{ url_for('digestmonkey.index') }}">Digest Monkey</a></li>
            <li><a href="{{ url_for('export.index') }}">Export Events</a></li>
        {% endif %}
        <li><a href="{{ url_for('frontend.page') }}">{{ _("About Site ") }}</a></li>
    </ul>
    {% if user.is_admin %}
    <ul>
      <li class="title">Admin</li>
      <li><a href="{{ url_for('auth.teams') }}">Teams</a></li>
        <li><a href="{{ url_for('auth.create_user') }}">New User</a></li>
    </ul>
    {% endif %}

    <ul>
      <li class="title">Accounts</li>
      {% if user.is_authenticated %}
      <li><a href="{{ url_for('auth.profile') }}"><i class="fa fa-user"></i> {{ _("Profile") }}</a></li>
      <li><a href="{{ url_for('auth.logout') }}" data-confirm="{{ _('Do you want to logout?')}}" data-title="{{ _('Logout?') }}"><i class="fa fa-sign-out"></i> {{ _("Logout") }}</a></li>
      {% else %}
      <li><a href="{{ url_for('auth.login') }}"> {{ _("Login") }} </a></li>
      {% endif %}
    </ul>
</div>

admin_service/templates/page.html
{% extends "base.html" %}
{% set page_title = page.title %}

{% block content %}

{{ page.html|safe }}

{% endblock %}