admin_service/digestmonkey/models.py
from sqlalchemy.dialects.postgresql import ARRAY, JSON
from admin_service.extensions import db
from sqlalchemy.orm import backref, relationship


class DigestMonkeyConfig(db.Model):
    __tablename__ = 'mailchimpkeys'
    id = db.Column(db.Integer, primary_key=True)
    mailchimp_key = db.Column(db.String(100))
    templates_uri = db.Column(db.String(100))
    github_key = db.Column(db.String(100))
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    team = relationship("Team", backref=backref("digestmonkey_config", uselist=False))


class PublishedDigest(db.Model):
    __tablename__ = 'digests'
    id = db.Column(db.Integer, primary_key=True)
    events_data = db.Column(JSON)
    events_ids = db.Column(ARRAY(db.Integer))
    template = db.Column(db.String(100))
    preview = db.Column(db.Text)
    s_list = db.Column(db.String(20))
    s_list_name = db.Column(db.String(100))
    from_name = db.Column(db.String(100))
    from_email = db.Column(db.String(100))
    subject = db.Column(db.String(200))
    campaign_id = db.Column(db.String(20))
    web_id = db.Column(db.String(20))
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))
    team = relationship("Team", backref=backref("digests"))

admin_service/digestmonkey/__init__.py
from .views import digestmonkey

admin_service/digestmonkey/views.py
# -*- coding: utf-8 -*-
from collections import OrderedDict, defaultdict

import dateutil.parser
from flask import (Blueprint, render_template, g, request, url_for,
                   redirect)
import trafaret as t

from admin_service.digestmonkey import mailchimp_utils
from admin_service.digestmonkey.github_utils import get_github_repo
from admin_service.digestmonkey.mailchimp_utils import get_mailchimp_api
from admin_service.digestmonkey.models import DigestMonkeyConfig, PublishedDigest
from flask.ext.login import login_required
from admin_service.digestmonkey.utils.digest import init_digest, set_variable, set_default_template_variables, \
    generate_preview
from admin_service.digestmonkey.utils.query_parser import parse_named_values
from admin_service.events.views import EventsList
from ..extensions import cache, db

digestmonkey = Blueprint('digestmonkey', __name__, url_prefix='/digestmonkey/', template_folder="templates")


@digestmonkey.route('index')
@login_required
def index():
    if not g.user.team.digestmonkey_config or \
            not g.user.team.digestmonkey_config.mailchimp_key or \
            not g.user.team.digestmonkey_config.templates_uri or \
            not g.user.team.digestmonkey_config.github_key:
        return redirect(url_for('digestmonkey.setup'))
    sess = db.session()
    r = sess.query(PublishedDigest).order_by(PublishedDigest.id.desc()).limit(5).all()
    return render_template('digestmonkey/index.html', last_campaigns=r)


SETUP_FORM = t.Dict({
                     'mailchimp_key': t.String,
                     'templates_uri': t.String(allow_blank=True),
                     'github_key': t.String(allow_blank=True),
                    }).ignore_extra('_csrf_token')


@digestmonkey.route('setup', methods=['POST', 'GET'])
@login_required
def setup():
    g.errors = []
    if request.method == 'POST':
        do_setup()
        if not g.errors:
            return redirect(url_for('digestmonkey.index'))
    return render_template('digestmonkey/setup.html',
                           errors=g.errors,
                           initial=g.user.team.digestmonkey_config)


def do_setup():
    try:
        data = SETUP_FORM.check(request.form.to_dict())
    except t.DataError as e:
        g.errors += ['{}: {}'.format(key, value)
                     for key, value in e.error.items()]
        return

    sess = db.session()
    if not g.user.team.digestmonkey_config:
        config = DigestMonkeyConfig(team_id=g.user.team.id)
        sess.add(config)
        sess.commit()
    else:
        config = g.user.team.digestmonkey_config
    sess.query(DigestMonkeyConfig).filter(DigestMonkeyConfig.id == config.id).update(data)
    sess.commit()


class EventsSubset(EventsList):

    template = 'digestmonkey/subset.html'
    def post(self):
        if request.form['submit'] == 'subset':
            events_list = [k for k, v in request.form.to_dict().items() if v == 'on']
            if not events_list:
                return redirect(request.url)
            params = parse_named_values(request.form['query'])
            subset_id = init_digest(events_list, params)
            return redirect(url_for('digestmonkey.choose_template', subset_id=subset_id))
        return redirect(request.url)


digestmonkey.add_url_rule('subset', view_func=login_required(EventsSubset.as_view('make_subset')))


@digestmonkey.route('choose-template/<subset_id>')
@login_required
def choose_template(subset_id):
    templates = [file for file in get_github_repo().get_dir_contents('/')
                 if file.name.endswith(".html") or file.name.endswith(".template")]
    if len(templates) == 1:
        set_variable(subset_id, 'template', templates[0].name)
        return redirect(url_for('digestmonkey.configure_template', subset_id=subset_id))
    else:
        return render_template('digestmonkey/choose_template.html',
                               templates=templates,
                               subset_id=subset_id,
                               subset=cache.get(subset_id))


@digestmonkey.route('choose-template/<subset_id>/<filename>')
@login_required
def template_chosen(subset_id, filename):
    set_variable(subset_id, 'template', filename)
    return redirect(url_for('digestmonkey.configure_template', subset_id=subset_id))


@digestmonkey.route('configure-template/<subset_id>', methods=['POST', 'GET'])
@login_required
def configure_template(subset_id):
    if request.method == 'POST':
        data = cache.get(subset_id)
        variables = request.form.to_dict()
        if '_csrf_token' in variables:
            del variables['_csrf_token']
        data['variables'] = variables
        cache.set(subset_id, data, timeout=60*60*24)
        return redirect(url_for('digestmonkey.preview', subset_id=subset_id))
    variables = set_default_template_variables(subset_id)
    return render_template('digestmonkey/configure_template.html',
                           subset_id=subset_id,
                           subset=cache.get(subset_id),
                           variables=OrderedDict(sorted(variables.items())))


@digestmonkey.route('preview/<subset_id>')
@login_required
def preview(subset_id):
    generate_preview(subset_id)
    return redirect(url_for('digestmonkey.choose_maillist', subset_id=subset_id))


@digestmonkey.route('preview-content/<subset_id>')
@login_required
def preview_content(subset_id):
    data = cache.get(subset_id)
    return data['preview']


MAILLIST_SETUP_FORM = t.Dict({
                        'subject': t.String,
                        'from_name': t.String,
                        'from_email': t.String,
                        }).ignore_extra('_csrf_token')


@digestmonkey.route('choose-maillist/<subset_id>', methods=['POST', 'GET'])
@login_required
def choose_maillist(subset_id):
    data = cache.get(subset_id)
    g.errors = []
    if request.method == 'POST':
        url = do_create_campaign(data)
        if not g.errors:
            return redirect(url)

    s_list = request.args.get('s_list')
    initial = {}
    initial.update(request.form.to_dict())
    params = defaultdict(str, data['query_params'])

    if s_list:
        list_info = mailchimp_utils.get_list(s_list)

        subject = list_info['default_subject']
        if subject:
            initial['subject'] = subject.format(**params)

        from_name = list_info['default_from_name']
        if from_name:
            initial['from_name'] = from_name

        from_email = list_info['default_from_email']
        if from_email:
            initial['from_email'] = from_email

        data['s_list'] = s_list
        data['s_list_name'] = list_info['name']

    cache.set(subset_id, data, timeout=60*60*24)
    return render_template('digestmonkey/choose_maillist.html',
                           subset_id=subset_id,
                           subset=cache.get(subset_id),
                           lists=mailchimp_utils.list_list(),
                           s_list=s_list,
                           initial=initial,
                           errors=g.errors)


def do_create_campaign(data):
    try:
        data.update(MAILLIST_SETUP_FORM.check(request.form.to_dict()))
    except t.DataError as e:
        g.errors += ['{}: {}'.format(key, value)
                     for key, value in e.error.items()]
        return
    options = {
        'list_id': data['s_list'],
        'subject': data['subject'],
        'from_name': data['from_name'],
        'from_email': data['from_email'],
        }

    content = {
        'html': data['preview'],
    }

    r = get_mailchimp_api().campaigns.create('regular', options, content)
    url = "https://admin.mailchimp.com/campaigns/wizard/html-paste?id={}". \
        format(r['web_id'])

    d = PublishedDigest(events_data=data['list'],
                        events_ids=[int(e['id']) for e in data['list']],
                        template=data['template'],
                        preview=data['preview'],
                        s_list=data['s_list'],
                        s_list_name=data['s_list_name'],
                        from_name=data['from_name'],
                        from_email=data['from_email'],
                        subject=data['subject'],
                        campaign_id=r['id'],
                        web_id=r['web_id'],
                        team_id=g.user.team.id)
    sess = db.session()
    sess.add(d)
    sess.commit()

    return url


@digestmonkey.route('digest-details/<id_>')
@login_required
def digest_details(id_):
    sess = db.session()
    digest = sess.query(PublishedDigest).filter(PublishedDigest.id == int(id_)).first()
    return render_template('digestmonkey/digest_details.html',
                           digest=digest)


@digestmonkey.route('digest-details/<id_>/preview')
@login_required
def digest_details_preview(id_):
    sess = db.session()
    digest = sess.query(PublishedDigest).filter(PublishedDigest.id == int(id_)).first()
    return digest.preview

admin_service/digestmonkey/templates/digestmonkey/choose_maillist.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

<div class="grid-2 gutter-10">
    <div class="span-1">
        <p>Step 1: you have selected {{ subset.list|length }} events</p>
        <p><a href="{{ url_for('digestmonkey.choose_template', subset_id=subset_id) }}">Step 2</a>: you have selected template "{{ subset.template}}"</p>
        <p><a href="{{ url_for('digestmonkey.configure_template', subset_id=subset_id) }}">Step 3</a>: variables set for template</p>
        <h2>Step 4</h2>

        {% if not s_list %}
                <p>Select the Subscription List</p>
                <ul>
                        {% for id_, item in lists.items() %}
                        <li>
                                <a href="{{ url_for('digestmonkey.choose_maillist', subset_id=subset_id, s_list=id_) }}">
                                {{ item }}
                                </a>
                        </li>
                        {% endfor %}
                </ul>
        {% else %}
                {% for id_, item in lists.items() %}
                        {% if s_list == id_ %}
                                <p>You have selected the <b>"{{ item }}"</b> Subscribers List [<a href="{{ url_for('digestmonkey.choose_maillist', subset_id=subset_id) }}">change</a>]</p>
                        {% endif %}
                {% endfor %}
        {% endif %}

        {% for error in errors %}
            <p class="flakes-message error">{{ error }}</p>
        {% endfor %}

        {% if s_list %}
        <form class="grid-form" method="POST">
            <fieldset>
                <legend>Email properties</legend>
                <div data-row-span="1">
                    <div data-field-span="1">
                        <label>Subject</label>
                        <input type="text" name="subject" value="{% if initial.subject %}{{ initial.subject }}{% endif %}">
                    </div>
                </div>
                <div data-row-span="1">
                    <div data-field-span="1">
                        <label>"From:" Name</label>
                        <input type="text" name="from_name" value="{% if initial.from_name %}{{ initial.from_name }}{% endif %}">
                    </div>
                </div>
                <div data-row-span="1">
                    <div data-field-span="1">
                        <label>"From:" Email</label>
                        <input type="text" name="from_email" value="{% if initial.from_email %}{{ initial.from_email }}{% endif %}">
                    </div>
                </div>
            </fieldset>
            <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
            <br>
            <input type="submit" class="button-magenta bigger" value="Create MailChimp campaign">
        </form>
        {% endif %}
    </div>
    <div class="span-1">
        <fieldset class="flakes-information-box">
            <legend>Preview
                <a href="{{ url_for('digestmonkey.preview_content', subset_id=subset_id) }}" target="_blank">
                    <i class="fa fa-expand"></i>
                </a>
            </legend>
            <iframe src="{{ url_for('digestmonkey.preview_content', subset_id=subset_id) }}" width="100%"
                height="600px" frameborder="0"></iframe>
        </fieldset>
    </div>
</div>
{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/choose_template.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

<p>Step 1: you selected {{ subset.list|length }} events</p>
<h2>Step 2</h2>

<ul>
{% for template in templates %}
    <li><a href="{{ url_for('digestmonkey.template_chosen', subset_id=subset_id, filename=template.name) }}">{{ template.name }}</a>: [<a href="{{ template.html_url }}">on github</a>]</li>
{% endfor %}
</ul>

{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/configure_template.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

<p>Step 1: you selected {{ subset.list|length }} events</p>
<p><a href="{{ url_for('digestmonkey.choose_template', subset_id=subset_id) }}">Step 2</a>: you selected template "{{ subset.template}}"</p>
<h2>Step 3</h2>

<fieldset>
    <legend>Configure Template</legend>
    <form method="post">
        <ul>
            {% for variable,initial in variables.items() %}
            <li>
                <label>{{variable|replace('_',' ')|capitalize}}</label>
                <input type="text" placeholder="{{variable|replace('_',' ')|capitalize}}"
                       value="{{initial}}" name="{{ variable }}">
            </li>
            {% endfor %}
            <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
            <li>
                <button type="submit"
                    class="action button-magenta">Submit</button>
            </li>
        </ul>
    </form>
</fieldset>

{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/digest_details.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }}</h1>

<div class="grid-10 gutter-20">
    <div class="span-6">
        <fieldset class="flakes-information-box">
            <legend>General</legend>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Events list</dt>
                    <dd>
                        <ol>
                            {% for event in digest.events_data %}
                            <li><a href="{{ url_for('events.events_details', id_=event.id) }}">{{ event.title }}</a></li>
                            {% endfor %}
                        </ol>
                    </dd>
                </dl>
            </div>
        </fieldset>
    </div>
    <div class="span-4">
        <fieldset class="flakes-information-box">
            <legend>Email Properties</legend>

            <div class="grid-1">
                <dl class="span-1">
                    <dt>Subject</dt>
                    <dd>{{digest.subject}}</dd>
                </dl>
            </div>
            <div class="grid-2">
                <dl class="span-1">
                    <dt>From: name</dt>
                    <dd>{{ digest.from_name }}</dd>
                </dl>
                <dl class="span-1">
                    <dt>From: Email</dt>
                    <dd>{{ digest.from_email }}</dd>
                </dl>
            </div>
        </fieldset>

        <fieldset class="flakes-information-box">
            <legend>MailChimp</legend>

            <div class="grid-2">
                <dl class="span-1">
                    <dt>Subscribers List</dt>
                    <dd>{{ digest.s_list_name }}</dd>
                </dl>
                <dl class="span-1">
                    <dt>Campaign</dt>
                    <dd><a href="https://admin.mailchimp.com/campaigns/show?id={{ digest.web_id }}">Campaign on MailChimp</a></dd>
                </dl>
            </div>
        </fieldset>

        <fieldset class="flakes-information-box">
            <legend>Other</legend>

            <div class="grid-2">
                <dl class="span-1">
                    <dt>Template used</dt>
                    <dd>{{ digest.template }}</dd>
                </dl>
            </div>
        </fieldset>
    </div>

</div>
<br>
<fieldset class="flakes-information-box">
    <legend>Preview</legend>

    <iframe src="{{ url_for('digestmonkey.digest_details_preview', id_=digest.id ) }}" width="100%"
        height="600px" frameborder="0"></iframe>
</fieldset>

{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/index.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

<fieldset>
    <legend>Make the mailing campaign</legend>
    <p>To create the digest you need to</p>
    <ul>
        <li>Make events subset</li>
        <li>Choose and configure email template</li>
        <li>Send it to your subscribers using MailChimp</li>
    </ul>
    <a href="{{ url_for('digestmonkey.make_subset') }}" class="button-magenta bigger">Make events subset</a>
</fieldset>


<table class="flakes-table">
    <colgroup>
        <!--<col span="1" style="width:20px" />-->
        <col span="1" style="width:40%" />
    </colgroup>
    <thead>
        <tr>
            <!--<td><input type="checkbox"></td>-->
            <td>Subject</td>
            <td>Subscribers List</td>
            <td>MailChimp</td>
        </tr>
    </thead>
    <tbody class="list">
        {% for campaign in last_campaigns %}
        <tr>
          <!--<td><input type="checkbox"></td>-->
          <td><a href="{{ url_for('digestmonkey.digest_details', id_=campaign.id) }}">{{ campaign.subject }}</a></td>
          <td>{{ campaign.s_list_name }}</td>
          <td><a href="https://admin.mailchimp.com/campaigns/show?id={{ campaign.web_id }}">Open on MailChimp</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>

<div class="flakes-actions-bar">
    <a href="{{ url_for('digestmonkey.setup') }}" class="button-gray smaller">Setup</a>
</div>
{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/preview.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

<p>Step 1: you selected {{ subset.list|length }} events</p>
<p><a href="{{ url_for('digestmonkey.choose_template', subset_id=subset_id) }}">Step 2</a>: you selected template "{{ subset.template}}"</p>
<p><a href="{{ url_for('digestmonkey.configure_template', subset_id=subset_id) }}">Step 3</a>: variables set for template</p>
<h2>Step 4</h2>

<fieldset class="flakes-information-box">
    <legend>Preview</legend>
    <iframe src="{{ url_for('digestmonkey.preview_content', subset_id=subset_id) }}" width="100%"
        height="600px" frameborder="0"></iframe>
</fieldset>

<a href="{{ url_for('digestmonkey.choose_maillist', subset_id=subset_id) }}"
        class="action button-magenta">Approve</a>

{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/setup.html
{% extends "base.html" %}
{% set page_title = _('Digest Monkey') %}

{% block content %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>

{% for error in errors %}
    <p class="flakes-message error">{{ error }}</p>
{% endfor %}

<form class="grid-form" method="POST">
    <fieldset>
        <legend>Setup DigestMonkey</legend>
        <div data-row-span="1">
            <div data-field-span="1">
                <label>MailChimp API Key</label>
                <input type="text" name="mailchimp_key" value="{% if initial.mailchimp_key %}{{ initial.mailchimp_key }}{% endif %}">
            </div>
        </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label>GitHub API Key</label>
                <input type="text" name="github_key" value="{% if initial.github_key %}{{ initial.github_key }}{% endif %}">
            </div>
        </div>
        <div data-row-span="1">
            <div data-field-span="1">
                <label>GitHub Digest Templates repository (in format "username/reponame")</label>
                <input type="text" name="templates_uri" value="{% if initial.templates_uri %}{{ initial.templates_uri }}{% endif %}" placeholder="username/reponame">
            </div>
        </div>
    </fieldset>
    <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
    <br>
    <input type="submit" class="button-green bigger" value="Save">
</form>
{% endblock %}

admin_service/digestmonkey/templates/digestmonkey/subset.html
{% extends "events/events.html" %}
{% set page_title = _('Digest Monkey') %}

{% block header %}
<h1>{{ _("Digest Monkey") }} <i class="fa fa-hand-peace-o"></i></h1>
{% endblock %}
<h2>Step 1</h2>

{% block action_buttons %}
{% endblock %}

{% block events_list %}
{{ super() }}
<button type="submit" name="submit" form="events_list"
            class="action button-magenta bigger right" value="subset">Select</button>
{% endblock %}