admin_service/events/models.py
from admin_service.extensions import db


class SuggestedEvent(db.Model):
    __tablename__ = 'suggested_events'

    title = db.Column(db.Unicode(256), nullable=False)
    agenda = db.Column(db.UnicodeText(), nullable=False)
    social = db.Column(db.UnicodeText(), nullable=True)
    image_url = db.Column(db.String(500), nullable=True)
    level = db.Column(db.String(20), default='NONE', nullable=False)
    place = db.Column(db.Unicode(256), nullable=True)
    when_start = db.Column(db.DateTime(), nullable=False)
    when_end = db.Column(db.DateTime(), nullable=True)
    only_date = db.Column(db.Boolean(), default=True, nullable=False)
    registration_url = db.Column(db.String(500), nullable=True)
    team = db.Column(db.Integer, db.ForeignKey('teams.id'), nullable=False)
    submitter_email = db.Column(db.String(256), nullable=False)
    secret = db.Column(db.String(256), nullable=False,
                       doc='secret key to edit the suggested event',
                       primary_key=True)

    def to_dict(self):
        dict_ = {}
        for key in self.__mapper__.c.keys():
            dict_[key] = getattr(self, key)
        return dict_

admin_service/events/__init__.py
from .views import events

admin_service/events/client/__init__.py
import json
import requests


class EventsServiceAPIError(Exception):
    def __init__(self, errors=None):
        if not errors:
            errors = []
        super().__init__()
        self.errors = errors

    def __str__(self):
        return '; '.join(self.errors)


class EventsServiceAPI:
    def __init__(self, url):
        self.url = url
        self.session = requests.Session()

    def register_provider(self, name):
        response = self.session.post('{}/providers'.format(self.url),
                                     json={'name': name})
        return response.json()['key']

    def get_events(self, api_key, offset=0, count=10, sorting=None, query=None):
        if not sorting:
            sorting = ''
        response = self.session.get('{}/events?count={}&offset={}&order_by={}&query={}'.
                                    format(self.url, count, offset, sorting, query),
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        data = response.json()
        events = []
        for event in data.pop('events'):
            event['metainfo'] = json.loads(event.pop('metainfo'))
            events.append(event)
        data['events'] = events
        return data

    def get_event(self, api_key, id_):
        response = self.session.get('{}/events/{}'.
                                    format(self.url, id_),
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        data = response.json()
        data['metainfo'] = json.loads(data.pop('metainfo'))
        return data

    def add_event(self, api_key, metainfo, **kwargs):
        data = kwargs.copy()
        data.update({'metainfo': json.dumps(metainfo)})
        response = self.session.post('{}/events'.
                                     format(self.url),
                                     json=data,
                                     headers={'Client-Key': api_key})
        self.process_errors(response)
        return response.headers['location']

    def edit_event(self, api_key, id_, metainfo, **kwargs):
        data = kwargs.copy()
        data.update({'metainfo': json.dumps(metainfo)})
        response = self.session.put('{}/events/{}'.
                                    format(self.url, id_),
                                    json=data,
                                    headers={'Client-Key': api_key})
        self.process_errors(response)
        return response.headers['location']

    def delete_event(self, api_key, id_):
        response = self.session.delete('{}/events/{}'.
                                       format(self.url, id_),
                                       headers={'Client-Key': api_key})
        self.process_errors(response)

    def process_errors(self, response):
        if response.status_code > 299:
            if response.status_code == 400:
                raise EventsServiceAPIError(['{}: {} [api]'.format(k, v) for k, v in response.json().items()])
            raise EventsServiceAPIError(['Events Service returned {} error'.format(response.status_code)])

admin_service/events/views.py
import uuid
import logging
import re

from flask import (Blueprint, render_template, g, request, url_for,
    current_app, send_from_directory, json, redirect, make_response, abort)

from flask.ext.login import login_required
from flask.views import MethodView
from admin_service.events.client import EventsServiceAPIError
from admin_service.events.models import SuggestedEvent

from ..extensions import pages, csrf, cache, db
import trafaret as t
import dateutil.parser
from datetime import datetime


events = Blueprint('events', __name__, url_prefix='/events/', template_folder="templates")

logger = logging.getLogger(__name__)


class EventsList(MethodView):
    template = 'events/events.html'

    def get(self):
        offset = int(request.args.get('offset', 0))
        count = int(request.args.get('count', 25))
        query = request.args.get('query', '')
        page = int(offset/count) + 1
        r = current_app.events_api.get_events(g.user.team.events_token,
                                              offset=offset,
                                              count=count,
                                              sorting='-when_start',
                                              query=query)
        events = []
        for event in r.pop('events'):
            sess = db.session()
            q = sess.query(PublishedDigest).\
                filter(PublishedDigest.events_ids.contains([int(event['id'])]))
            event['published'] = q.all()
            events.append(event)
        r['events'] = events
        return render_template(self.template,
                               events_data=r,
                               offset=offset,
                               count=count,
                               page=page,
                               query=query)

events.add_url_rule('list', view_func=login_required(EventsList.as_view('events_list')))


def strip_newlines(data):
    data = data.strip()
    data = re.sub(r'(<br/>|<br>|<p><br></p>|<p></p>)*$', '', data)
    data = data.strip()
    return data


EVENT_CREATION_FORM = t.Dict({
                             'title': t.String,
                             'agenda': t.String >> strip_newlines,
                             'social': t.String(allow_blank=True) >> strip_newlines,
                             'place': t.String(allow_blank=True),
                             'registration_url': t.URL(allow_blank=True),
                             'image_url': t.URL(allow_blank=True) | t.String(max_length=0, allow_blank=True),
                             'level': t.Enum('NONE', 'TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR'),
                             t.Key('special', default=False): t.StrBool,
                             'when_start': t.String,
                             'when_end': t.String(allow_blank=True),
                             t.Key('include_time', to_name='only_date', default=False):
                                 t.StrBool >> (lambda x: not x),
                            }).ignore_extra('_csrf_token', 'submit')


@events.route('event/create', methods=['GET', 'POST'])
@login_required
def create_event():
    g.errors = []
    if request.method == 'POST':
        id_ = do_create_event()
        if not g.errors:
            if request.form.get('submit') == 'save_add_more':
                return redirect(url_for('events.create_event', added=1))
            return redirect(url_for('events.events_details', id_=id_))
    initial = request.form.to_dict()
    if not initial:
        initial['only_date'] = False
    return render_template('events/event_create.html', errors=g.errors,
                           initial=initial)


def do_create_event():
    try:
        data = EVENT_CREATION_FORM.check(request.form.to_dict())
        logger.info(json.dumps(data))
    except t.DataError as e:
        g.errors += ['{}: {}'.format(key, value)
                     for key, value in e.error.items()]
        return
    id_ = None
    try:
        created = current_app.events_api.add_event(g.user.team.events_token,
                                                   {'creator': g.user.username},
                                                   **data)
        id_ = created.split('/')[-1]
    except EventsServiceAPIError as e:
        g.errors += e.errors
    return id_


@events.route('details/<id_>')
@login_required
def events_details(id_):
    r = current_app.events_api.get_event(g.user.team.events_token, id_)
    return render_template('events/event_details.html',
                           event=r)


@events.route('edit/<id_>', methods=['GET', 'POST'])
@login_required
def edit_event(id_):
    r = current_app.events_api.get_event(g.user.team.events_token, id_)
    g.errors = []
    if request.method == 'POST':
        do_edit_event(id_)
        if not g.errors:
            if request.form.get('submit') == 'Edit_add_more':
                return redirect(url_for('events.create_event', added=1))
            return redirect(url_for('events.events_details', id_=id_))
    return render_template('events/event_create.html', errors=g.errors,
                           initial=r,
                           edit=True)


def do_edit_event(id_):
    try:
        data = EVENT_CREATION_FORM.check(request.form.to_dict())
    except t.DataError as e:
        g.errors += ['{}: {}'.format(key, value)
                     for key, value in e.error.items()]
        return
    try:
        current_app.events_api.edit_event(g.user.team.events_token,
                                          id_,
                                          {'creator': g.user.username},
                                          **data)
    except EventsServiceAPIError as e:
        g.errors += e.errors


@events.route('list', methods=['POST'])
def list_actions():
    if request.form['submit'] == 'delete':
        action_id = uuid.uuid4().hex
        to_delete = [k for k, v in request.form.to_dict().items() if v == 'on']
        if to_delete:
            data = {'action': 'delete', 'items': to_delete}
            cache.set(action_id, data, timeout=5*60)
            return render_template('events/approve.html', action='delete {} events'.format(len(to_delete)), action_id=action_id)
    elif request.form['submit'] == 'preview':
        events_list = [k for k, v in request.form.to_dict().items() if v == 'on']
        if events_list:
            subset_id = init_digest(events_list, {})
            set_variable(subset_id, 'template', 'main.html')  # FIXME: hardcoded
            set_variable(subset_id, 'variables', {})  # FIXME: hardcoded
            set_default_template_variables(subset_id)
            generate_preview(subset_id)
            return redirect(url_for('digestmonkey.preview_content', subset_id=subset_id))
    elif request.form['submit'] == 'approve':
        data = cache.get(request.form['action_id'])
        if not data:
            return render_template('events/error.html', errors=['Expired'])
        if data['action'] == 'delete':
            for item in data['items']:
                try:
                    current_app.events_api.delete_event(g.user.team.events_token, item)
                except EventsServiceAPIError as e:
                    return render_template('events/error.html', errors=e)

    return redirect(request.url)


from admin_service.digestmonkey.models import PublishedDigest


class SuggestedEventsList(MethodView):
    template = 'events/suggested_events.html'

    def get(self):
        events = SuggestedEvent.query.filter(SuggestedEvent.team == g.user.team.id).all()
        return render_template(self.template,
                               events=events)

events.add_url_rule('suggested/list',
                    view_func=login_required(SuggestedEventsList.as_view('suggested_events_list')))


@events.route('suggested/details/<secret>')
@login_required
def suggested_events_details(secret):
    event = SuggestedEvent.query.get(secret)
    date_formatted = datetime.strftime(event.when_start, "%m.%d.%Y")
    r = current_app.events_api.get_events(g.user.team.events_token,
                                          offset=0,
                                          count=50,
                                          sorting='when_start',
                                          query="when_start >= '{} 00:00' and when_start <= '{} 23:59'".format(date_formatted, date_formatted))
    print("when_start >= '{}' and when_start <= '{}'".format(date_formatted, date_formatted))
    return render_template('events/suggested_event_details.html',
                           event=event,
                           same_day_events=r)


@events.route('suggested/accept/<secret>', methods=['GET', 'POST'])
@login_required
def accept_suggested_event(secret):
    g.errors = []
    if request.method == 'POST':
        id_ = do_create_event()
        if not g.errors:
            SuggestedEvent.query.filter(SuggestedEvent.secret == secret).delete()
            db.session.commit()
            return redirect(url_for('events.events_details', id_=id_))

    initial = request.form.to_dict()
    event = SuggestedEvent.query.get(secret)
    initial.update(event.to_dict())
    initial['when_start'] = initial['when_start'].isoformat()
    if initial['when_end']:
        initial['when_end'] = initial['when_end'].isoformat()
    if not initial['registration_url']:
        initial['registration_url'] = ''
    return render_template('events/event_create.html', errors=g.errors,
                           initial=initial)


@events.route('suggested/decline/<secret>')
@login_required
def decline_suggested_event(secret):
    SuggestedEvent.query.filter(SuggestedEvent.secret == secret).delete()
    db.session.commit()
    return redirect(url_for('events.suggested_events_list'))


from admin_service.digestmonkey.utils.digest import init_digest, set_variable, set_default_template_variables, \
    generate_preview

admin_service/events/templates/events/approve.html
{% extends "base.html" %}
{% set page_title = _('Events DB') %}

{% block content %}
Do you really want to {{ action }}?
<form method="post">
    <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
    <input name=action_id type=hidden value="{{ action_id }}">
    <button type="submit" name="submit"
            class="action button-darkblue smaller" value="approve">YES</button>
    <button type="submit" name="submit"
            class="action button-darkblue smaller" value="cancel">NO</button>
</form>
{% endblock %}

admin_service/events/templates/events/error.html
{% extends "base.html" %}
{% set page_title = _('Events DB') %}

{% block content %}

{% for error in errors %}
    <p class="flakes-message error">{{ error }}</p>
{% endfor %}

{% endblock %}

admin_service/events/templates/events/event_details.html
{% extends "base.html" %}
{% set page_title = _('Events DB') %}

{% block content %}
<h1>{{ _("Event details") }}</h1>

<div class="grid-10 gutter-20">
    <div class="span-6">
        <fieldset class="flakes-information-box">
            <legend>General</legend>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Title</dt>
                    <dd>{{event.title}}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Agenda</dt>
                    <dd>{%if event.agenda %}{{event.agenda|safe}}{%endif%}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Social [Technical info. Not display anywhere]</dt>
                    <dd>{%if event.social %}{{event.social|safe}}{%endif%}</dd>
                </dl>
            </div>
        </fieldset>
    </div>
    <div class="span-4">
        <fieldset class="flakes-information-box">
            <legend>Details</legend>

            <div class="grid-1">
                <dl class="span-1">
                    <dt>Place</dt>
                    <dd>{{event.place}}</dd>
                </dl>
            </div>
            <div class="grid-2">
                <dl class="span-1">
                    <dt>Starts at</dt>
                    <dd>
                      {% if not event.only_date %}
                        {{ event.when_start|strfdatetime }}
                      {% else %}
                        {{ event.when_start|strfdate }}
                      {% endif %}
                    </dd>
                </dl>
                {% if event.when_end %}
                <dl class="span-1">
                    <dt>Ends at</dt>
                    <dd>
                      {% if not event.only_date %}
                        {{ event.when_end|strfdatetime }}
                      {% else %}
                        {{ event.when_end|strfdate }}
                      {% endif %}
                    </dd>
                </dl>
                {% endif %}
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Special</dt>
                    <dd>
                        {% if event.special %}
                        <i class="fa fa-check-circle-o"></i>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Level</dt>
                    <dd>{{ event.level }}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Registration URL</dt>
                    <dd>
                        {% if event.registration_url %}
                        <a href="{{ event.registration_url }}">{{ event.registration_url }}</a>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Image URL</dt>
                    <dd>
                        {% if event.image_url %}
                        <a href="{{ event.image_url }}">{{ event.image_url }}</a>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Last edited by</dt>
                    <dd>
                        {{ event.metainfo.creator }}
                    </dd>
                </dl>
            </div>
        </fieldset>
    </div>

</div>
<br>
<a class="action button-green bigger right" href="{{ url_for('events.edit_event', id_=event.id) }}">Edit</a>

{% endblock %}

admin_service/events/templates/events/suggested_event_details.html
{% extends "base.html" %}
{% set page_title = _('Events DB') %}

{% block content %}
<h1>{{ _("Suggested event details") }}</h1>

<div class="grid-10 gutter-60">
    <div class="span-7">
        <fieldset class="flakes-information-box">
            <legend>General</legend>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Title</dt>
                    <dd>{{event.title}}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Agenda</dt>
                    <dd>{%if event.agenda %}{{event.agenda|safe}}{%endif%}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Social [Technical info. Not display anywhere]</dt>
                    <dd>{%if event.social %}{{event.social|safe}}{%endif%}</dd>
                </dl>
            </div>
        </fieldset>
    </div>
    <div class="span-3">
        {% if same_day_events.events %}
        <fieldset class="flakes-information-box">
            <legend>Information</legend>
            <div class="grid-1">
                <dl class="span-1">
                    <p class="flakes-message tip"><i class="fa fa-exclamation-triangle"></i>Please check that the event you're going to accept is not the duplicate of following events that are already in the database
                    </p>
                    <dt>Events in database planned on same day</dt>
                    <dd>
                        <ul>
                        {% for event in same_day_events.events %}
                            <li>
                                <a href="{{ url_for('events.events_details', id_=event.id) }}" target="_blank">{{event.title}}</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </dd>
                </dl>
            </div>
        </fieldset>
        {% endif %}
        <fieldset class="flakes-information-box">
            <legend>Details</legend>

            <div class="grid-1">
                <dl class="span-1">
                    <dt>Place</dt>
                    <dd>{{event.place}}</dd>
                </dl>
            </div>
            <div class="grid-2">
                <dl class="span-1">
                    <dt>Starts at</dt>
                    <dd>
                      {% if not event.only_date %}
                        {{ event.when_start|strftime('%Y-%m-%d %H:%M') }}
                      {% else %}
                        {{ event.when_start|strftime('%Y-%m-%d') }}
                      {% endif %}
                    </dd>
                </dl>
                {% if event.when_end %}
                <dl class="span-1">
                    <dt>Ends at</dt>
                    <dd>
                      {% if not event.only_date %}
                        {{ event.when_end|strftime('%Y-%m-%d %H:%M') }}
                      {% else %}
                        {{ event.when_end|strftime('%Y-%m-%d') }}
                      {% endif %}
                    </dd>
                </dl>
                {% endif %}
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Special</dt>
                    <dd>
                        {% if event.special %}
                        <i class="fa fa-check-circle-o"></i>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Level</dt>
                    <dd>{{ event.level }}</dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Registration URL</dt>
                    <dd>
                        {% if event.registration_url %}
                        <a href="{{ event.registration_url }}">{{ event.registration_url }}</a>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Image URL</dt>
                    <dd>
                        {% if event.image_url %}
                        <a href="{{ event.image_url }}">{{ event.image_url }}</a>
                        {% else %}
                        <i class="fa fa-ban"></i>
                        {% endif %}
                    </dd>
                </dl>
            </div>
            <div class="grid-1">
                <dl class="span-1">
                    <dt>Submitted by</dt>
                    <dd>
                        {{ event.submitter_email }}
                    </dd>
                </dl>
            </div>
        </fieldset>
    </div>

</div>
<br>

<div class="flakes-actions-bar">
    <a class="action button-green bigger left"
       href="{{ url_for('events.accept_suggested_event', secret=event.secret) }}">Accept</a>
    <a class="action button-red bigger right"
       href="{{ url_for('events.decline_suggested_event', secret=event.secret) }}">Decline</a>
</div>
{% endblock %}

admin_service/events/templates/events/suggested_events.html
{% extends "base.html" %}
{% set page_title = _('Events DB') %}

{% block content %}

{% block header %}
<h1>{{ _("Suggested Events") }}</h1>
{% endblock %}

<div class="grid-1">
    <div class="span-1">
        {% block events_list %}
        <form id="events_list" method="post">
            <table class="flakes-table">
                <colgroup>
                    <col span="1" style="width:20px" />
                </colgroup>
                <thead>
                    <tr>
                        <td></td>
                        <td class="name">Title</td>
                        <td>When</td>
                        <td>Submitter</td>
                        <td>Actions</td>
                    </tr>
                </thead>
                <tbody class="list">
                    {% for event in events %}
                        <tr>
                            <td><input type="checkbox" class="eventSelect" name="{{ event.secret }}"></td>
                            <td><a href="{{ url_for('events.suggested_events_details', secret=event.secret) }}">
                                {{ event.title }}</a>
                            </td>
                            <td>
                              {% if not event.only_date %}
                                {{ event.when_start|strftime('%Y-%m-%d %H:%M') }}
                              {% else %}
                                {{ event.when_start|strftime('%Y-%m-%d') }}
                              {% endif %}
                            </td>
                            <td>
                                {{ event.submitter_email }}
                            </td>
                            <td>

                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <input name=_csrf_token type=hidden value="{{ csrf_token() }}">
        </form>
        {% endblock %}
    </div>
</div>
{% endblock %}